# Feel free to disable non-critical HA parts during devel by commenting lines out
# Generated in hadk by executing: rpm/dhd/helpers/add_new_device.sh

Description: Pattern with packages for f5321 configurations
Name: jolla-configuration-f5321
Requires:
- pattern:jolla-hw-adaptation-kugo

- patterns-sailfish-applications
- patterns-sailfish-ui
- patterns-sailfish-cellular-apps

- droid-config-f5321-sailfish
- droid-config-f5321-pulseaudio-settings
- droid-config-f5321-policy-settings
- droid-config-f5321-preinit-plugin
- droid-config-f5321-flashing
- droid-config-f5321-bluez5
- droid-hal-version-f5321

- droid-system-f5321

- sailfish-content-graphics-z@ICON_RES@
- csd
- sd-utils
- geoclue-provider-mlsdb
- jolla-settings-system-flashlight
- mapplauncherd-booster-silica-qt5-media

Summary: Jolla Configuration f5321

